#!/usr/bin/env bash
cd ..
source .env
git init
git config user.email $GIT_EMAIL
git config user.name $GIT_NAME
git config core.autocrlf input
git branch -M main
git remote add origin $REMOTE_REPO
git remote set-url origin $REMOTE_REPO
npx husky init
echo "npx --no -- commitlint --edit $1" > ./.husky/commit-msg
echo "uvx pre-commit run --hook-stage pre-commit" > ./.husky/pre-commit
