#!/usr/bin/env python3
import os
from pathlib import Path

import rtoml
from dotenv import load_dotenv

load_dotenv()
data = rtoml.load(Path(__file__).parent.parent / "pyproject.toml")

project_name = data["project"]["name"]
os.system("rm -rf ./dist")
if project_name:
    os.system(f"sudo rm -rf ./{project_name}.egg-info")
os.system("python -m build")
os.system(
    f"python -m twine upload dist/* -u {os.environ['PYPI_U']} -p {os.environ['PYPI_P']}",
)
