name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  tox:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm,
             windows-latest, windows-11-arm,
             macos-13, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        exclude:
          - os: windows-11-arm
            python-version: "3.10"
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Rust (for Rust-based Python packages)
      uses: dtolnay/rust-toolchain@stable

    - name: Upgrade pip and install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run tox
      run: |
        TOX_ENV=py${{ matrix.python-version }}
        TOX_ENV=${TOX_ENV//./}
        tox -e $TOX_ENV
