name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  tox:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm,
             windows-latest, windows-11-arm,
             macos-13, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        include:
          - os: ubuntu-latest
            python-version: "3.13"
            run_lint: true
        exclude:
          - os: windows-11-arm
            python-version: "3.10"
    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup test Python environment
      uses: ./.github/actions/setup-test-env
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run lint
      if: matrix.run_lint == true
      run: tox -e format,type

    - name: Run test
      shell: bash
      run: |
        TOX_ENV=py${{ matrix.python-version }}
        TOX_ENV=${TOX_ENV//./}
        tox -e $TOX_ENV
